### ISSUE TITLE
Not spawning

### ISSUE THREAD

**Issue by kyleh666** [BurntRouter/ATimeMod#2]
Due to a bad push, the code didn't end up on my computer where I compile. I didn't test it like the terrible programmer I am. Working on patch for 1.7.10 and making an update for 1.8

**Comment by BurntRouter** [comment]
Could you send me your log. Also I've decided to work 1.8 so if there is a problem I see I'll patch it. Thanks.

**Comment by kyleh666** [comment]
how do i send my log?

**Comment by BurntRouter** [comment]
Go to your Minecraft directory.
Go to the folder labeled "logs"
Send the file called "latest.log" to my email which is router@burntrouter.info

**Comment by BurntRouter** [comment]
Alright so I'm moving the update to a project I'm calling ATime2
It's a major rework of the mod hopefully fixing everything and adding a ton of stuff.
